name: Docker Build and Push

on:
  push:
    branches:
      - github_actions


jobs:
  build-and-push:
    runs-on: self-hosted

    steps:
    
      - uses: actions/checkout@v3
      
      - name: Build the Docker image
        run: docker build . -f ./Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/node_onlogn

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/node_onlogn

      - name: Remove Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/node_onlogn
